PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX base: <https://nobias-project.eu/>publ
SELECT ?User (count(distinct ?PubID) as ?PublisherDiversityCount)
WHERE {
# Getting Usercred through Usercredlat(U)
?inst_arg <https://nobias-project.eu/hasAtom> ?user_atom .
?inst_arg rdf:type <https://nobias-project.eu/RandomAtomInstArgument> .
?inst_arg <https://nobias-project.eu/hasArgument> ?user_arg_instance .
?user_atom <https://nobias-project.eu/rva_name> ?user_atom_name .
?user_arg_instance <https://nobias-project.eu/inst_arg_name> ?User
#FILTER regex(?SharedByUser, "<Type specific UserID here>", "i") .
FILTER regex(?user_atom_name, "USERCREDLAT", "i") .
# Getting User argument from ObservedAtom UserShare(N,U)
?obs_inst_arg rdf:type <https://nobias-project.eu/ObsvAtomInstArgument> .
?obs_inst_arg <https://nobias-project.eu/hasAtom> ?obs_atom .
?obs_inst_arg <https://nobias-project.eu/position> "2" .
?obs_inst_arg <https://nobias-project.eu/hasArgument> ?user_arg_instance .
?obs_inst_arg2 <https://nobias-project.eu/hasAtom> ?obs_atom .
?obs_inst_arg2 <https://nobias-project.eu/position> "1" .
?obs_inst_arg2 <https://nobias-project.eu/hasArgument> ?news_arg_instance .
?news_arg_instance <https://nobias-project.eu/inst_arg_name> ?NewsID .

# Getting Publisher argument from ObservedAtom NewsShare(N,P)
?obs_inst_arg_news rdf:type <https://nobias-project.eu/ObsvAtomInstArgument> .
?obs_inst_arg_news <https://nobias-project.eu/hasAtom> ?news_pub_atom .
?news_pub_atom <https://nobias-project.eu/instantiatesFrom> <https://nobias-project.eu/Atom/Atom3> .
?obs_inst_arg_news <https://nobias-project.eu/position> "2" .
?obs_inst_arg_news <https://nobias-project.eu/hasArgument> ?pub_arg_instance .
?obs_inst_arg2_news <https://nobias-project.eu/hasAtom> ?news_pub_atom .
?obs_inst_arg2_news <https://nobias-project.eu/position> "1" .
?obs_inst_arg2_news <https://nobias-project.eu/hasArgument> ?news_arg_instance_news .
?news_arg_instance_news <https://nobias-project.eu/inst_arg_name> ?NewsID .
?pub_arg_instance <https://nobias-project.eu/inst_arg_name> ?PubID .

}
GROUP BY (?User)
ORDER BY DESC(?PublisherDiversityCount)
