#BuzzFeed
#Counting news with prediction probability for Class:Fake

SELECT DISTINCT  ?o1 (count(distinct ?news) as ?num)
WHERE {
        
        ?run <http://interpretme.org/vocab/hasRun> <http://interpretme.org/entity/1696608392435> .
        ?run <http://interpretme.org/vocab/hasEntity> ?news.
        ?run <http://interpretme.org/vocab/hasClass> <http://interpretme.org/entity/1>. 
       ?run <http://interpretme.org/vocab/hasPredictionProbability> ?o1.
} GROUP BY ?o1