# At what iteration does an RVA converge?
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
Select distinct  (SAMPLE(?news) AS ?news) ?rva (SAMPLE(?name) AS ?AtomName) (SAMPLE(?arg_name) AS ?Type) (SAMPLE(?credibility) AS ?Credibility) (SAMPLE(?lastValue) AS ?lastValue) ((MAX(xsd:integer(?lastIterationNumber)) +1) AS ?convergencePoint) WHERE{
    ?rva rdf:type <https://nobias-project.eu/RandomVariableAtom>  ;
         <https://nobias-project.eu/rva_name> ?name ;
         # Change to Data2 for Politifact
   		 <https://nobias-project.eu/hasDataset> <https://nobias-project.eu/Dataset/Data1> ;
         <https://nobias-project.eu/hasCredibilityClass> ?credibility ;
         <https://nobias-project.eu/instantiatesFrom> ?parentAtom ;
    	 <https://nobias-project.eu/value> ?lastValue .
    ?atom_arg <https://nobias-project.eu/hasAtom> ?parentAtom .
    ?atom_arg <https://nobias-project.eu/hasArgument> ?argument .
    ?argument <https://nobias-project.eu/arg_name> ?arg_name .
    ?iterationRva <https://nobias-project.eu/hasAtom> ?rva .
    ?iterationRva a <https://nobias-project.eu/IterationRVA> .
    ?iterationRva <https://nobias-project.eu/currentValue> ?iterationValue .
    ?iterationRva <https://nobias-project.eu/hasIteration> ?lastIteration .
    ?lastIteration <https://nobias-project.eu/iterationNumber> ?lastIterationNumber .
    FILTER(?iterationValue != ?lastValue).
    ?instArg <https://nobias-project.eu/originatesFrom> ?news .
    ?AtomInst <https://nobias-project.eu/hasArgument> ?instArg .
    ?AtomInst <https://nobias-project.eu/hasAtom> ?rva .

} 
GROUP BY ?rva


