#  MaxTerm incompatibility value progression
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX base: <https://nobias-project.eu/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?maxTerm ?iterationNumber ?value
WHERE {
?iterTerm a <https://nobias-project.eu/IterationTerm> .
?iterTerm <https://nobias-project.eu/hasDataset> <https://nobias-project.eu/Dataset/Data2>  .
?iterTerm <https://nobias-project.eu/hasTerm> ?maxTerm .
?iterTerm <https://nobias-project.eu/hasIteration> ?iteration .
?iteration <https://nobias-project.eu/iterationNumber> ?iterationNumber .
?iterTerm <https://nobias-project.eu/currentValue> ?value .       
} 
ORDER BY ?maxTerm xsd:integer(?iterationNumber)

