# User diversity for each news (No of unique users)
select ?news (COUNT(?user) as ?userDiversityCount) where { 
        ?sharingBehavior a <https://nobias-project.eu/SharingBehavior> .
        ?sharingBehavior <https://nobias-project.eu/News> ?news .
        ?sharingBehavior <https://nobias-project.eu/SocialMediaUser> ?user .
        ?news <https://nobias-project.eu/associatedTo> <https://nobias-project.eu/Dataset/Data2> .
	} 
GROUP BY ?news
ORDER BY DESC(?userDiversityCount)
