# Publishers and their published news 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?publisher ?news ?publisherURL ?newsTitle ?newsURL
WHERE {
?publisher <https://nobias-project.eu/publishes> ?news .
?publisher <https://nobias-project.eu/sourceName> ?publisherURL .
?news    <https://nobias-project.eu/hasNewsTitle> ?newsTitle .
?news <https://nobias-project.eu/hasNewsUrl> ?newsURL .
FILTER regex(xsd:string(?news), "Buzzfeed", "i") .
} 
