# What are the news articles and their info (title, publisher, URL...)
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?s ?newsTitle ?newsURL ?newsSource ?groundTruth ?relatedAtom ?optimizedValue
WHERE {
?s rdf:type <https://nobias-project.eu/News> ;
   <https://nobias-project.eu/hasNewsTitle> ?newsTitle;
   <https://nobias-project.eu/hasNewsUrl> ?newsURL;
   <https://nobias-project.eu/hasSource> ?newsSource;
   <https://nobias-project.eu/hasGroundTruth> ?groundTruth .
?instArg <https://nobias-project.eu/originatesFrom> ?s .
?AtomInst <https://nobias-project.eu/hasArgument> ?instArg .
?AtomInst <https://nobias-project.eu/hasAtom> ?relatedAtom .
?relatedAtom <https://nobias-project.eu/value> ?optimizedValue .
?relatedAtom <https://nobias-project.eu/instantiatesFrom> <https://nobias-project.eu/Atom/Atom2> .
?relatedAtom <https://nobias-project.eu/hasDataset> <https://nobias-project.eu/Dataset/Data2> .
} 
