# Average weight for each  rule of the JointCredibilityModel in a given dataset

PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
select ?rule ?dataset (AVG(xsd:float(?weightValue)) AS ?avgWeightForRule) where { 
	?rule <https://nobias-project.eu/hasWeight> ?weightInstance .
    ?weightInstance <https://nobias-project.eu/hasWeight> ?weightValue .
    ?weightInstance <https://nobias-project.eu/hasFold> ?CVFold .
    # This filter only considers the JointCredibility model
    ?CVFold <https://nobias-project.eu/model> "Model2" .
    ?CVFold <https://nobias-project.eu/dataset> ?dataset .
} 
GROUP BY ?rule ?dataset
ORDER BY ASC(xsd:integer(?foldNumber))
