# Number of connected of ground rules a RVA is occurring in
PREFIX base: <https://nobias-project.eu/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?item ?name ?dataset ?rva (COUNT(?rva) AS ?groundRuleCount) ?inferredValue ?credibilityClass ?profile
WHERE {
?rva rdf:type <https://nobias-project.eu/RandomVariableAtom> ;
   base:hasDataset ?dataset ;
   <https://nobias-project.eu/hasCredibilityClass> ?credibilityClass ;
   <https://nobias-project.eu/value> ?inferredValue ;
   base:rva_name ?name .
   BIND(IF(CONTAINS(?name, "FAKENEWS"), "News",
       IF(CONTAINS(?name, "USERCREDLAT"), "User", "Publisher")
        ) AS ?profile)
    #FILTER regex(?profile, "News", "i") .
?groundrule base:hasGroundAtom ?rva .
?instArg <https://nobias-project.eu/originatesFrom> ?item .
?AtomInst <https://nobias-project.eu/hasArgument> ?instArg .
?AtomInst <https://nobias-project.eu/hasAtom> ?rva .

} 
GROUP BY ?name ?rva ?inferredValue ?credibilityClass ?profile ?dataset ?item
ORDER BY DESC (?groundRuleCount)
