# For publisher Review get MediaBiasFactcheck score vs inferred score
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?s ?publisherURL ?inferredCredibilityBuzzfeed ?inferredCredibilityPolitifact ?MBFCCredibility
WHERE {
?s rdf:type <https://nobias-project.eu/Publisher> ;
   <https://nobias-project.eu/sourceName> ?publisherURL .
    OPTIONAL {
        # Get inferredCred for Buzzfeed
        ?instArg <https://nobias-project.eu/originatesFrom> ?s .
        ?RvaAtomInst a <https://nobias-project.eu/RandomAtomInstArgument> .
        ?RvaAtomInst <https://nobias-project.eu/hasArgument> ?instArg .
        ?RvaAtomInst <https://nobias-project.eu/hasAtom> ?relatedRVA .
        ?relatedRVA <https://nobias-project.eu/instantiatesFrom> <https://nobias-project.eu/Atom/Atom4> .
        ?relatedRVA <https://nobias-project.eu/value> ?inferredCredibilityBuzzfeed .
        ?relatedRVA <https://nobias-project.eu/hasDataset> <https://nobias-project.eu/Dataset/Data1> .
    }
    OPTIONAL {
        # Get inferredCred for Politifact            
        ?instArg2 <https://nobias-project.eu/originatesFrom> ?s .
        ?RvaAtomInst2 a <https://nobias-project.eu/RandomAtomInstArgument> .
        ?RvaAtomInst2 <https://nobias-project.eu/hasArgument> ?instArg2 .
        ?RvaAtomInst2 <https://nobias-project.eu/hasAtom> ?relatedRVA2 .
        ?relatedRVA2 <https://nobias-project.eu/instantiatesFrom> <https://nobias-project.eu/Atom/Atom4> .
        ?relatedRVA2 <https://nobias-project.eu/value> ?inferredCredibilityPolitifact .
        ?relatedRVA2 <https://nobias-project.eu/hasDataset> <https://nobias-project.eu/Dataset/Data2> ;
    }


    OPTIONAL {
        ?s <https://nobias-project.eu/credibilityAssessment> ?MBFCCredibility
    }
} 
