PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX base: <https://nobias-project.eu/>
SELECT ?rva ?name ?value ?credibility
WHERE {
?rva rdf:type base:RandomVariableAtom ;
   base:rva_name ?name ;
   base:value ?value ;
   base:hasCredibilityClass ?credibility ;
FILTER regex(?name, "FAKENEWS", "i") .
} 
