PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX base: <https://nobias-project.eu/>
SELECT ?name ?rva (COUNT(?rva) AS ?groundRuleCount)
WHERE {
?rva rdf:type <https://nobias-project.eu/RandomVariableAtom> ;
   base:rva_name ?name .
?groundrule base:hasGroundAtom ?rva
} 
GROUP BY ?name ?rva
ORDER BY DESC (?groundRuleCount)
