# Bias information documentation - Querying bias information
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
select ?dataset (COUNT(*) AS ?biasInformation) where { 
     {
        SELECT ?dataset WHERE {?dataset a <http://www.w3.org/ns/dcat#Dataset> .}
    }

    { 
        ?biasAssessment <https://nobias-project.eu/hasDocumentationType> <https://nobias-project.eu/BiasDocumentation> .
    	?biasAssessment ?r ?t . 
    FILTER (!isBlank(?t))
    FILTER EXISTS { ?biasAssessment ?asseses ?entity . ?entity ?associatedTo ?dataset . } .

        
    }
      UNION
    { 
        ?biasAssessment <https://nobias-project.eu/hasDocumentationType> <https://nobias-project.eu/BiasDocumentation> .
    	?h ?r ?biasAssessment .
        FILTER (!isBlank(?h))
        FILTER EXISTS { ?biasAssessment ?asseses ?entity . ?entity ?associatedTo ?dataset . } .
    }

}
GROUP BY ?dataset
