# Comparing Fake News Score with Avg UserCred of users that share that news + deviation between the two

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX base: <https://nobias-project.eu/>
SELECT ?NewsID (SAMPLE(?value) as ?FakeNewsScore) (Count(?NewsID) AS ?SharingUsers) (Avg(xsd:float(?user_value)) AS ?avgCred) ((abs(1-xsd:float(?FakeNewsScore)-?avgCred)) AS ?deviation)
WHERE {
    # Get all RVAs Fakenews(N)
    ?rva_instance rdf:type <https://nobias-project.eu/RandomVariableAtom> ;
    	<https://nobias-project.eu/rva_name> ?name ;
       	# Change to Data2 for Politifact
   		<https://nobias-project.eu/hasDataset> <https://nobias-project.eu/Dataset/Data1> ;
       	<https://nobias-project.eu/value> ?value .
    FILTER regex(?name, "FAKENEWS", "i") .
    # Extracting news argument from RVA
    ?rand_inst_arg <https://nobias-project.eu/hasAtom> ?rva_instance .
    ?rva_instance <https://nobias-project.eu/value> ?news_cred .
    ?rand_inst_arg <https://nobias-project.eu/hasArgument> ?news_arg .
    ?obs_inst_arg <https://nobias-project.eu/hasArgument> ?news_arg .
    ?news_arg <https://nobias-project.eu/inst_arg_name> ?NewsID .
    # Getting User argument from ObservedAtom UserShare(N,U)
    ?obs_inst_arg rdf:type <https://nobias-project.eu/ObsvAtomInstArgument> .
    ?obs_inst_arg <https://nobias-project.eu/hasAtom> ?obs_atom .
    ?obs_inst_arg2 <https://nobias-project.eu/hasAtom> ?obs_atom .
    ?obs_inst_arg2 <https://nobias-project.eu/position> "2" .
    ?obs_inst_arg2 <https://nobias-project.eu/hasArgument> ?user_arg_instance .
    # Getting Usercred through Usercredlat(U)
    ?inst_arg <https://nobias-project.eu/hasAtom> ?user_atom .
    ?inst_arg rdf:type <https://nobias-project.eu/RandomAtomInstArgument> .
    ?inst_arg <https://nobias-project.eu/hasArgument> ?user_arg_instance .
    ?user_atom <https://nobias-project.eu/rva_name> ?user_atom_name .
    FILTER regex(?user_atom_name, "USERCREDLAT", "i") .
    ?user_atom <https://nobias-project.eu/value> ?user_value .
}
GROUP BY ?NewsID
