# Getting the average change of RVA values per iteration
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX base: <https://nobias-project.eu/>
SELECT (SAMPLE(?currentIteration) AS ?iteration) (AVG(?changeToPrevious) AS ?avgChangeInPercent)
WHERE {
# Get all RVAs Fakenews(N)
?rva_instance rdf:type <https://nobias-project.eu/RandomVariableAtom> ;
   <https://nobias-project.eu/rva_name> ?name ;
FILTER regex(?name, "FAKENEWS", "i") .
# FILTER regex(?name, "<Enter specific news here, e.g. BuzzFeed_Fake_89>", "i") .
?iteration_rva <https://nobias-project.eu/hasAtom> ?rva_instance .
?iteration_rva a <https://nobias-project.eu/IterationRVA> .
?iteration_rva <https://nobias-project.eu/currentValue> ?currentValue .
?iteration_rva <https://nobias-project.eu/hasIteration> ?currentIteration .
?currentIteration <https://nobias-project.eu/iterationNumber> ?iterationNumber .
    BIND(xsd:string(xsd:integer(?iterationNumber) - 1) AS ?prevIterationNumber) .
?prevIteration <https://nobias-project.eu/iterationNumber> ?prevIterationNumber .
?iteration_rva2 <https://nobias-project.eu/hasIteration> ?prevIteration .
?iteration_rva2 <https://nobias-project.eu/hasAtom> ?rva_instance .
?iteration_rva2 <https://nobias-project.eu/currentValue> ?prevValue .
BIND(abs(xsd:float(?prevValue) / xsd:float(?currentValue) - 1) as ?changeToPrevious) .
}
GROUP BY ?iterationNumber
