PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX base: <https://nobias-project.eu/>
SELECT ?NewsID ?PublishedBy ?pub_atom
WHERE {
    # Getting Publisher through Pubcredlat(U)
    ?inst_arg <https://nobias-project.eu/hasAtom> ?pub_atom .
    ?inst_arg rdf:type <https://nobias-project.eu/RandomAtomInstArgument> .
    ?inst_arg <https://nobias-project.eu/hasArgument> ?pub_arg_instance .
    ?pub_atom <https://nobias-project.eu/rva_name> ?pub_atom_name .
    ?pub_arg_instance <https://nobias-project.eu/inst_arg_name> ?PublishedBy
    # FILTER regex(?PublishedBy, "<Type specific Publisher here>", "i") .
    FILTER regex(?pub_atom_name, "PUBCREDLAT", "i") .
    # Getting User argument from ObservedAtom UserShare(N,U)
    ?obs_inst_arg rdf:type <https://nobias-project.eu/ObsvAtomInstArgument> .
    ?obs_inst_arg <https://nobias-project.eu/hasAtom> ?obs_atom .
    ?obs_inst_arg <https://nobias-project.eu/position> "2" .
    ?obs_inst_arg <https://nobias-project.eu/hasArgument> ?pub_arg_instance .
    ?obs_inst_arg2 <https://nobias-project.eu/hasAtom> ?obs_atom .
    ?obs_inst_arg2 <https://nobias-project.eu/position> "1" .
    ?obs_inst_arg2 <https://nobias-project.eu/hasArgument> ?news_arg_instance .
    ?news_arg_instance <https://nobias-project.eu/inst_arg_name> ?NewsID
    #FILTER regex(?NewsID, "<Type specific news here>", "i") .
}
ORDER BY ?NewsID
