PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX base: <https://nobias-project.eu/>
SELECT DISTINCT ?Publisher
WHERE {
    # Getting Publishers
    ?pub_atom <https://nobias-project.eu/rva_name> ?pub_atom_name .
    FILTER regex(?pub_atom_name, "PUBCREDLAT", "i") .
    ?pub_obs_arg <https://nobias-project.eu/hasAtom> ?pub_atom .
    ?pub_obs_arg <https://nobias-project.eu/position> "1" .
    ?pub_obs_arg <https://nobias-project.eu/hasArgument> ?pub_arg_instance .
    ?pub_arg_instance <https://nobias-project.eu/inst_arg_name> ?Publisher .
}
