# Equalized Odds 1: True positive rate difference (TPR), overrepresented news vs not overrepresented


PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?positiveCountOver ?positiveCountNotOver ?truePositivesOver ?truePositivesNotOver (?truePositivesOver / xsd:float(?positiveCountOver) AS ?tprOver) (?truePositivesNotOver / xsd:float(?positiveCountNotOver) AS ?tprNotOver) (?tprOver - ?tprNotOver AS ?tprDifference)
WHERE {
    {
        SELECT (COUNT(*) AS ?positiveCountOver)
        WHERE {
        ?s rdf:type <https://nobias-project.eu/News> ;
           <https://nobias-project.eu/hasNewsTitle> ?newsTitle;
           <https://nobias-project.eu/hasNewsUrl> ?newsURL;
           <https://nobias-project.eu/hasSource> ?newsSource;
           <https://nobias-project.eu/hasGroundTruth> ?groundTruth;
           <https://nobias-project.eu/isOverrepresented> "true"^^xsd:boolean .
        ?instArg <https://nobias-project.eu/originatesFrom> ?s .
        ?AtomInst <https://nobias-project.eu/hasArgument> ?instArg .
        ?AtomInst <https://nobias-project.eu/hasAtom> ?relatedAtom .
        ?relatedAtom <https://nobias-project.eu/instantiatesFrom> <https://nobias-project.eu/Atom/Atom2> .
        ?relatedAtom <https://nobias-project.eu/value> ?atomValue .
        ?relatedAtom a <https://nobias-project.eu/RandomVariableAtom> .
        BIND((IF(xsd:float(?atomValue) >= 0.5,1,0)) as ?RoundedPrediction) .
        # Filter for positives
        FILTER (?RoundedPrediction = 1) .
        } 
    }
    
    {
        SELECT (COUNT(*) AS ?positiveCountNotOver)
        WHERE {
        ?s rdf:type <https://nobias-project.eu/News> ;
           <https://nobias-project.eu/hasNewsTitle> ?newsTitle;
           <https://nobias-project.eu/hasNewsUrl> ?newsURL;
           <https://nobias-project.eu/hasSource> ?newsSource;
           <https://nobias-project.eu/hasGroundTruth> ?groundTruth;
           <https://nobias-project.eu/isOverrepresented> "false"^^xsd:boolean .
        ?instArg <https://nobias-project.eu/originatesFrom> ?s .
        ?AtomInst <https://nobias-project.eu/hasArgument> ?instArg .
        ?AtomInst <https://nobias-project.eu/hasAtom> ?relatedAtom .
        ?relatedAtom <https://nobias-project.eu/instantiatesFrom> <https://nobias-project.eu/Atom/Atom2> .
        ?relatedAtom <https://nobias-project.eu/value> ?atomValue .
        ?relatedAtom a <https://nobias-project.eu/RandomVariableAtom> .
        BIND((IF(xsd:float(?atomValue) >= 0.5,1,0)) as ?RoundedPrediction) .
        # Filter for positives
        FILTER (?RoundedPrediction = 1) .
        } 
    }
    
    {
        SELECT (COUNT(*) AS ?truePositivesOver)
        WHERE {
        ?s rdf:type <https://nobias-project.eu/News> ;
           <https://nobias-project.eu/hasNewsTitle> ?newsTitle;
           <https://nobias-project.eu/hasNewsUrl> ?newsURL;
           <https://nobias-project.eu/hasSource> ?newsSource;
           <https://nobias-project.eu/hasGroundTruth> "1";
           <https://nobias-project.eu/isOverrepresented> "true"^^xsd:boolean .
        ?instArg <https://nobias-project.eu/originatesFrom> ?s .
        ?AtomInst <https://nobias-project.eu/hasArgument> ?instArg .
        ?AtomInst <https://nobias-project.eu/hasAtom> ?relatedAtom .
        ?relatedAtom <https://nobias-project.eu/instantiatesFrom> <https://nobias-project.eu/Atom/Atom2> .
        ?relatedAtom <https://nobias-project.eu/value> ?atomValue .
        ?relatedAtom a <https://nobias-project.eu/RandomVariableAtom> .
        BIND((IF(xsd:float(?atomValue) >= 0.5,1,0)) as ?RoundedPrediction) .
        # Filter for positives
        FILTER (?RoundedPrediction = 1) .
        } 
    }
    {
        SELECT (COUNT(*) AS ?truePositivesNotOver)
        WHERE {
        ?s rdf:type <https://nobias-project.eu/News> ;
           <https://nobias-project.eu/hasNewsTitle> ?newsTitle;
           <https://nobias-project.eu/hasNewsUrl> ?newsURL;
           <https://nobias-project.eu/hasSource> ?newsSource;
           <https://nobias-project.eu/hasGroundTruth> "1";
           <https://nobias-project.eu/isOverrepresented> "false"^^xsd:boolean .
        ?instArg <https://nobias-project.eu/originatesFrom> ?s .
        ?AtomInst <https://nobias-project.eu/hasArgument> ?instArg .
        ?AtomInst <https://nobias-project.eu/hasAtom> ?relatedAtom .
        ?relatedAtom <https://nobias-project.eu/instantiatesFrom> <https://nobias-project.eu/Atom/Atom2> .
        ?relatedAtom <https://nobias-project.eu/value> ?atomValue .
        ?relatedAtom a <https://nobias-project.eu/RandomVariableAtom> .
        BIND((IF(xsd:float(?atomValue) >= 0.5,1,0)) as ?RoundedPrediction) .
        # Filter for positives
        FILTER (?RoundedPrediction = 1) .
        } 
    }
} 
